services:
  postgres:
    container_name: dhn_db
    image: postgres:latest
    ports:
      - 9852:5432
    volumes:
      - DHNpostgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

volumes:
  DHNpostgres:
